# Generated by Django 3.0.5 on 2020-04-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200419_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_run_out',
            field=models.BooleanField(default=False, verbose_name='Is the product run out of storage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product title'),
        ),
    ]
