# Generated by Django 3.0.5 on 2020-04-20 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified At'),
        ),
    ]
