# Generated by Django 3.0.5 on 2020-04-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20200420_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
