# Generated by Django 3.0.5 on 2020-04-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20200420_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active ?'),
        ),
    ]
