# Generated by Django 3.0.5 on 2020-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_command_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='client_cin',
            field=models.CharField(max_length=20, unique=True, verbose_name='Client CIN'),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_token',
            field=models.CharField(max_length=10, unique=True, verbose_name='Command Token'),
        ),
    ]
